"""change into nullable the paper_size and the color_mode on service_price table

Revision ID: b3b051522057
Revises: c70b44752a13
Create Date: 2026-09-30 13:50:51.475215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3b051522057'
down_revision: Union[str, Sequence[str], None] = 'c70b44752a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_prices', 'paper_size',
               existing_type=postgresql.ENUM('A4', 'Short', 'Long', name='paper_size'),
               nullable=True)
    op.alter_column('service_prices', 'color_mode',
               existing_type=postgresql.ENUM('bw', 'color', name='color_mode'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_prices', 'color_mode',
               existing_type=postgresql.ENUM('bw', 'color', name='color_mode'),
               nullable=False)
    op.alter_column('service_prices', 'paper_size',
               existing_type=postgresql.ENUM('A4', 'Short', 'Long', name='paper_size'),
               nullable=False)
    # ### end Alembic commands ###
