"""add services and pricing

Revision ID: c70b44752a13
Revises: cbb27d2211c3
Create Date: 2026-09-29 13:12:32.635315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c70b44752a13'
down_revision: Union[str, Sequence[str], None] = 'cbb27d2211c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('service_type', sa.Enum('print', 'xerox', 'scan', name='service_type'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'service_type', name='uq_tenant_service_type')
    )
    op.create_table('service_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('paper_size', sa.Enum('A4', 'Short', 'Long', name='paper_size'), nullable=False),
    sa.Column('color_mode', sa.Enum('bw', 'color', name='color_mode'), nullable=False),
    sa.Column('price_per_page', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'paper_size', 'color_mode', name='uq_service_price_option')
    )
    op.create_index(op.f('ix_service_prices_service_id'), 'service_prices', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_prices_service_id'), table_name='service_prices')
    op.drop_table('service_prices')
    op.drop_table('services')
    # ### end Alembic commands ###
